topic-exchange-name: street-cam-exchange
routing-key: street.cam.*
queue-name: street.cam.image
offset-start: ${OFFSET-START}
offset-end: ${OFFSET-END}
rate: 1800000

spring:
  rabbitmq:
    host: ${RABBITMQ-HOST}
