version: "3"

services:
    rabbitmq:
        image: rabbitmq:3.7.17-management
        ports:
          - 5672:5672
          - 15672:15672
      
    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:6.5.3
        volumes:
          - esdata:/usr/share/elasticsearch/data
        environment:
          - cluster.name=street-cam-app
          - bootstrap.memory_lock=true
          - "ES_JAVA_OPTS=-Xms256m -Xmx256m"
          - xpack.security.enabled=false
        ulimits:
          memlock:
            soft: -1
            hard: -1
        ports:
          - "9200:9200"
          
    kibana:
        image: docker.elastic.co/kibana/kibana:6.5.3
        ports:
          - "5601:5601"
        environment:
          - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
          - "ES_JAVA_OPTS=-Xms256m -Xmx256m"
        depends_on:
          - elasticsearch

    street-cam-loader-1:
        build: ./street-cam-loader
        environment:
          - RABBITMQ-HOST=rabbitmq
          - OFFSET-START=0
          - OFFSET-END=1000
          - JAVA_OPTS=-Xmx128m -Xms128m
          - WAIT_HOSTS=rabbitmq:15672
          - WAIT_HOSTS_TIMEOUT=300
        depends_on:
          - rabbitmq

    # street-cam-loader-2:
    #     build: ./street-cam-loader
    #     environment:
    #       - RABBITMQ-HOST=rabbitmq
    #       - OFFSET-START=1000
    #       - OFFSET-END=2000
    #     depends_on:
    #       - rabbitmq

    street-cam-classification:
        build: ./street-cam-classification
        ports:
          - "5000:80"

    street-cam-aggregator:
        build: ./street-cam-aggregator
        environment:
          - ELASTICSEARCH-HOST=elasticsearch
          - DETECTION-API=http://street-cam-classification/api
          - RABBITMQ-HOST=rabbitmq
          - JAVA_OPTS=-Xmx128m -Xms128m
          - WAIT_HOSTS=street-cam-classification:80,elasticsearch:9300,rabbitmq:15672
          - WAIT_HOSTS_TIMEOUT=300
        depends_on:
          - rabbitmq
          - elasticsearch
          - street-cam-classification

volumes:
    esdata: