version: "3"

services:
    rabbitmq:
        image: rabbitmq:3.7.17-management
        ports:
          - 5672:5672
          - 15672:15672
      
    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:6.5.3
        volumes:
          - esdata:/usr/share/elasticsearch/data
        environment:
          - cluster.name=street-cam-app
          - bootstrap.memory_lock=true
          - "ES_JAVA_OPTS=-Xms256m -Xmx256m"
          - xpack.security.enabled=false
        ulimits:
          memlock:
            soft: -1
            hard: -1
        ports:
          - "9200:9200"
          
    kibana:
        image: docker.elastic.co/kibana/kibana:6.5.3
        ports:
          - "80:5601"
        environment:
          - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
          - "ES_JAVA_OPTS=-Xms256m -Xmx256m"

    street-cam-loader-1:
        image: aleknik/street-cam-loader:latest
        environment:
          - RABBITMQ-HOST=rabbitmq
          - OFFSET-START=0
          - OFFSET-END=1000
          - JAVA_OPTS=-Xmx128m -Xms128m
          - WAIT_HOSTS=rabbitmq:15672
          - WAIT_HOSTS_TIMEOUT=3000

    # street-cam-loader-2:
    #     build: ./street-cam-loader
    #     environment:
    #       - RABBITMQ-HOST=rabbitmq
    #       - OFFSET-START=1000
    #       - OFFSET-END=2000
    #     depends_on:
    #       - rabbitmq

    # street-cam-classification:
    #     image: aleknik/street-cam-classification:latest
    #     ports:
    #       - "5000:80"

    street-cam-aggregator:
        image: aleknik/street-cam-aggregator:latest
        environment:
          - ELASTICSEARCH-HOST=elasticsearch
          - DETECTION-API=http://89902f29.ngrok.io/api
          - RABBITMQ-HOST=rabbitmq
          - JAVA_OPTS=-Xmx128m -Xms128m
          - WAIT_HOSTS= 89902f29.ngrok.io:80,elasticsearch:9300,rabbitmq:15672
          - WAIT_HOSTS_TIMEOUT=3000

volumes:
    esdata: