server.port: 8081
queue-name: street.cam.image
detection-api: ${DETECTION-API}

elasticsearch.clustername: street-cam-app
elasticsearch.host: ${ELASTICSEARCH-HOST}
elasticsearch.port: 9300

spring:
  rabbitmq:
    host: ${RABBITMQ-HOST}